baseURL = "/"
# canonifyURLs = true
defaultContentLanguage = "en"
disableLanguages = ["ru"]
paginate = "6"
relativeURLs = true
summaryLength = "50"
title = "Prizma"
# [Languages.en]
# contentDir = "content/en"
# home = "Home"
# languageCode = "en-us"
# languageName = "En"
# weight = 3
[Languages.ru]
contentDir = "content/ru"
home = "Главная"
languageCode = "ru"
languageName = "Ру"
weight = 2

[Languages.en]
contentDir = "content/en"
home = "Home"
languageCode = "en"
languageName = "ENG"
weight = 1



[outputs]
home = ["HTML", "RSS", "JSON"]
[sitemap]
ChangeFreq = "daily"
Priority = 0.6
Weight = [["main", "1"], ["sub2", "0.8"], ["sub3", "0.6"]]
enableRobotsTXT = true

[params]
CIO_site_id = "XXX"
GTM = "GTM-WHBQ3BV"
develop = "Anastasiia_Berest"
author = "Prizma"

logo = "./images/logo.svg"
logo_dark = "./images/logo.svg"
logo_description = "Prizma"

site_name = "Prizma"
site_url = "#"

description = "Is a simple ecnosystem of interconnected crypto products designed for the mass adoption of cryptocurrencies."

# search
search = true

# soc

[[params.plugins.js]]
link = "plugins/js/jquery.min.js"



[params.preloader]
enable = true
preloader = ""

[taxonomies]
category = "categories"
tag = "tags"


############################# socials #################################
[[params.soc]]
icon = "fb"
link = "#"
[[params.soc]]
icon = "im"
link = "#"
[[params.soc]]
icon = "tm"
link = "#"
[[params.soc]]
icon = "ytb"
link = "#"
[[params.soc]]
icon = "email"
link = "#"

############################# footer #################################
[params.footer]
    copyright = "Prizma invest &copy; 2024"


[[menu.footer]]
weight = 1
name = "Terms of Service"
URL = "/terms"
[[menu.footer]]
weight = 2
name = "Privacy Policy"
URL = "/policy"
[[menu.footer]]
weight = 3
name = "Manage Cookies"
URL = "/cookie"




[[menu.header]]
weight = 1
name = "About us"
URL = "/"
[[menu.header]]
weight = 2
name = "Design"
URL = "/"
[[menu.header]]
weight = 3
name = "Projects"
URL = "/"
[[menu.header]]
weight = 4
name = "Collections"
URL = "/"
[[menu.header]]
weight = 5
name = "Contacts"
URL = "/"

